### ISSUE TITLE
Feature Request: Notify Users if Input Code is Already Well-formatted

### ISSUE THREAD

**Issue by darylf** [dec-land/gd-format#1]
**Description**

I tried entering some code on the Format page (https://www.gdscriptformatter.com/format). The output was great, but then I quickly realized that the output matched my input. It would be nice if the tool simply told me that the input code had great formatting and no work was required.

**Expected Behavior**

When the Format button is clicked, if the input code is already well-formatted, the tool should notify the user that no formatting is required, instead of appearing to reformat the code.

**Comment by dec-land** [comment]
I can add that, should be able to do it later tonight :)
